# Generated by Django 5.1.2 on 2024-10-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(default='available', max_length=50),
        ),
    ]
