# Generated by Django 5.1.2 on 2024-10-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_genre_alter_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.TextField(default='m8.jpg'),
        ),
    ]
