# Generated by Django 5.1.2 on 2024-10-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_movie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.TextField(default='https://www.youtube.com/embed/0HY6QFlBzUY?autoplay=1'),
        ),
    ]
