# Generated by Django 5.1.2 on 2024-10-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_movie_trailer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='image_ava',
        ),
        migrations.AddField(
            model_name='movie',
            name='image_cover',
            field=models.TextField(default='m8.jpg'),
        ),
    ]
