# Generated by Django 5.1.2 on 2024-10-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_image_movie_image_ava_movie_image_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_ava',
            field=models.TextField(default='https://cinema.momocdn.net/img/76909001427055070-rkbse0ifgemkVtJKm7qWKy0vqj5.jpg'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_cover',
            field=models.TextField(default='https://cinema.momocdn.net/img/76909001873562492-AaYdXkEqExgG66p55J677Qnagpf.jpg'),
        ),
    ]
